const {
  MONGO_URI,
  MONGO_DEBUG,
  MONGO_SSL_CA,
  MONGO_SSL_CERT,
  MONGO_SSL_KEY,
  JWT_SECERET,
  TOKEN_VALIDITY,
  ENCRYPT_ALGO,
  ENCRYPT_KEY,
  ALLOW_CORS_ORIGIN,
  ALLOW_CORS_METHODS
} = process.env

const MONGO_CONFIG = {
  URI: MONGO_URI,
  DEBUG: MONGO_DEBUG,
  SSl_CA: MONGO_SSL_CA,
  SSl_CERT: MONGO_SSL_CERT,
  SSl_KEY: MONGO_SSL_KEY
}
const JWT_CONFIG = {
  SECERET: JWT_SECERET,
  TOKEN_VALIDITY,
  NO_AUTH_PATHS: [
    '/health-check',
    '/version'
    /* new RegExp(`^${STRING_VARIABLE}/otp/.*`), */
  ]
}
const ENCRYPTION = { ENCRYPT_ALGO, ENCRYPT_KEY }

const CORS_OPTIONS = ALLOW_CORS_ORIGIN === '*' ? undefined : {
  origin: ALLOW_CORS_ORIGIN.includes(',') ? ALLOW_CORS_ORIGIN.split(',') : ALLOW_CORS_ORIGIN,
  methods: ALLOW_CORS_METHODS,
  optionsSuccessStatus: 200
}

export { MONGO_CONFIG, JWT_CONFIG, CORS_OPTIONS, ENCRYPTION }
